baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '(=✪ᆽ✪=) darrens site'
theme = "cyberscape"

# Enable this for tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true

[[menu.main]]
name = "owasp-top10-list"
url = "/owasp-top10-list/"
weight = 1

[[menu.main]]
name = "about-me"
url = "/about-me/"
weight = 2

[[menu.main]]
name = "test"
url = "/test/"
weight = 3
